global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ai-agents"
    static_configs:
      - targets: ["ai-agents:8000"]
    scrape_interval: 30s
    metrics_path: "/metrics"

  - job_name: "agent-scheduler"
    static_configs:
      - targets: ["agent-scheduler:8001"]
    scrape_interval: 60s
